Albania=Europe
Angola=Africa
Argentina=South America
Armenia=Asia
Australia=Oceania
Austria=Europe
Bangladesh=Asia
Belarus=Europe
Belgium=Europe
Bolivia=South America
Brazil=South America
Bulgaria=Europe
Canada=North America
Chile=South America
China=Asia
Colombia=South America
Costa\ Rica=North America
Croatia=Europe
Cyprus=Europe
Czechia=Europe
Denmark=Europe
Dominican\ Republic=North America
Ecuador=South America
El\ Salvador=North America
Finland=Europe
France=Europe
Germany=Europe
Ghana=Africa
Greece=Europe
Guatemala=North America
Hong\ Kong=Asia
Hungary=Europe
Iceland=Europe
India=Asia
Iran=Middle East
Ireland=Europe
Israel=Middle East
Italy=Europe
Côte\ d'Ivoire=Africa
Japan=Asia
Kazakhstan=Asia
Kenya=Africa
Latvia=Europe
Lebanon=Middle East
Lithuania=Europe
Luxembourg=Europe
Malaysia=Asia
Mexico=North America
Morocco=Africa
Netherlands=Europe
New\ Zealand=Oceania
Nicaragua=North America
Nigeria=Africa
North\ Macedonia=Europe
Norway=Europe
Pakistan=Asia
Panama=North America
Peru=South America
Philippines=Asia
Poland=Europe
Portugal=Europe
Romania=Europe
Russia=Europe
Saudi\ Arabia=Middle East
Serbia=Europe
Singapore=Asia
South\ Africa=Africa
Spain=Europe
Sudan=Africa
Sweden=Europe
Switzerland=Europe
Taiwan=Asia
Tunisia=Africa
Turkey=Middle East
Ukraine=Europe
United\ Arab\ Emirates=Middle East
United\ Kingdom=Europe
United\ States=North America
Worldwide=Other / Unassigned
